theme: jekyll-theme-cayman
title: liko apps
description: We make small and cute apps!

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
